global:
  environment: development
  domain: majordwarf.com

frontend:
  enabled: true
  name: frontend
  replicaCount: 2
  image:
    repository: majordwarf-org/fe-app
    tag: latest
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: app.majordwarf.com
        paths:
          - path: /
            pathType: Prefix

backend:
  enabled: true
  name: backend
  replicaCount: 2
  image:
    repository: majordwarf-org/be-app
    tag: latest
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi
  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: api.majordwarf.com
        paths:
          - path: /
            pathType: Prefix

  config:
    postgres:
      host: "postgres-db"
      port: 5432
      database: "appdb"
      user: "app_user"
    kafka:
      brokers: "kafka-cluster-kafka-bootstrap:9092"
      topics:
        - name: "app-events"
          partitions: 3
          replicas: 3

postgresql:
  deployment:
    mode: "dedicated"  # Options: "dedicated" or "external"
    # Settings for dedicated deployment
    dedicated:
      enabled: true
      name: postgres-db
      instances:
        - name: postgres-instance
          replicas: 3
          memory: 2Gi
          cpu: 1.0
          storage: 10Gi
          database: appdb
          users:
            - name: app_user
              role: readWrite
    # Settings for external PostgreSQL
    external:
      host: "external-postgres.example.com"
      port: 5432
      database: "appdb"
      existingSecret: "external-postgres-secret"  # Secret containing username and password

kafka:
  deployment:
    mode: "dedicated"  # Options: "dedicated" or "external"
    # Settings for dedicated deployment
    dedicated:
      enabled: true
      name: kafka-cluster
      kafka:
        replicas: 3
        config:
          offsets.topic.replication.factor: 3
          transaction.state.log.replication.factor: 3
          transaction.state.log.min.isr: 2
        resources:
          requests:
            memory: 2Gi
            cpu: 1.0
          limits:
            memory: 2Gi
            cpu: 2.0
        storage:
          type: persistent-claim
          size: 20Gi
      zookeeper:
        replicas: 3
        storage:
          type: persistent-claim
          size: 10Gi
    # Settings for external Kafka
    external:
      brokers: "kafka-1:9092,kafka-2:9092,kafka-3:9092"
      ssl:
        enabled: false
        existingSecret: "external-kafka-ssl"  # Secret containing SSL certificates
      sasl:
        enabled: false
        mechanism: "PLAIN"  # PLAIN, SCRAM-SHA-256, SCRAM-SHA-512
        existingSecret: "external-kafka-sasl"  # Secret containing SASL credentials